how to check the normality of the data

In [1]:
data.head()

NameError: name 'data' is not defined

In [71]:
import pandas as pd
data=pd.read_csv("winequality-red.csv")

# what is my null hyphothesis?
#null hypothesis that the data was drawn from a normal distribution.

In [17]:
import numpy as np

if p<=result[1]:
    print("reject the null hyphothesis")
else:
    print("accept the null hyphothsis")

In [18]:
from scipy import stats
stats.normaltest(data['citric acid'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [19]:
sample_mean_iq=110
alpha=0.05
#ci=95%

In [20]:
mean_std_dev=15
mean_population=100

In [21]:
from numpy.random import randn

In [22]:
mean_std_dev*randn(50)+sample_mean_iq


array([ 73.11850267, 118.1011964 , 126.45320716,  80.79690937,
       112.40225254, 104.97794802, 103.03443972, 125.65874965,
       121.04792475, 129.63591018, 107.22024891, 135.24066249,
        90.61152679,  87.81878088, 109.27031066, 107.08928829,
        84.7351751 ,  87.26539612, 113.07833607, 102.61412875,
       140.54148298, 104.54927125, 115.45857095, 115.03040555,
       116.38225508, 112.7232079 , 107.02033541, 119.98459923,
        82.76029252,  90.61495491, 120.53835392, 107.55096219,
       105.41146781, 119.94741904, 110.57070795, 114.4769417 ,
       127.1584261 , 121.16491526, 139.77920786, 107.30646647,
       106.38487906, 119.00290529, 118.71197667,  73.7465907 ,
        91.22441048,  73.55248001,  98.31780408, 106.41381717,
       126.54221902, 128.761773  ])

In [23]:
data=mean_std_dev*randn(50)+mean_population


In [24]:
np.mean(data)

99.5575596232832

In [25]:
np.std(data)

12.248848213023514

In [26]:
null_hyphothesis_value=100

In [27]:
from statsmodels.stats.weightstats import ztest
ztest(data,value=null_hyphothesis_value,alternative='larger')

(-0.25284684593647483, 0.5998067171263217)

In [28]:
null_hyphothesis_value=130 

In [29]:
from statsmodels.stats.weightstats import ztest
ztest(data,value=null_hyphothesis_value,alternative='larger')

(-17.39731597052884, 1.0)

In [30]:
null_hyphothesis_value=105  ## accept null hyppothesis

In [31]:
from statsmodels.stats.weightstats import ztest
ztest(data,value=null_hyphothesis_value,alternative='larger')

(-3.110258366701869, 0.9990653811844302)

# t_test


#ztest vs test
sample size less than 30
pop var/pop std won't be there

one-sample t test(with respect to one independent sample)
two-sample t test(with respect to two independent sample)
paired t-test(two sample from the sample population on different time interval)

In [32]:
import random
import numpy as np
np.random.randint(10,50,50)


array([19, 26, 46, 42, 31, 36, 15, 32, 14, 19, 49, 32, 24, 22, 23, 45, 22,
       39, 25, 10, 23, 35, 36, 20, 38, 30, 16, 46, 36, 37, 43, 31, 18, 47,
       17, 38, 20, 41, 28, 21, 38, 46, 40, 19, 34, 39, 47, 13, 39, 13])

In [33]:
population=np.random.randint(10,50,50)

In [34]:
population

array([36, 28, 26, 17, 26, 12, 36, 17, 23, 35, 46, 39, 11, 10, 45, 19, 39,
       20, 30, 41, 45, 32, 33, 14, 12, 49, 48, 26, 16, 47, 27, 33, 26, 29,
       35, 48, 26, 34, 11, 41, 24, 38, 44, 13, 47, 24, 12, 21, 27, 44])

In [35]:
sample1=np.random.choice(population,20)
sample1

array([14, 16, 48, 27, 24, 29, 49, 19, 28, 33, 29, 17, 48, 14, 24, 21, 26,
       16, 48, 44])

In [36]:
sample2=np.random.choice(population,20)
sample2

array([26, 29, 39, 36, 13, 20, 27, 19, 26, 45, 39, 47, 33, 35, 10, 36, 45,
       41, 28, 36])

In [37]:
sample1.mean()


28.7

In [38]:
np.mean(sample1)

28.7

In [39]:
sample2.mean()


31.5

In [40]:
my_cricket_score=[22, 38, 19, 15, 48, 11, 10, 49, 47, 38, 10, 25, 46, 10, 21, 24, 29,36, 25, 24]

In [41]:
my_cricket_score

[22,
 38,
 19,
 15,
 48,
 11,
 10,
 49,
 47,
 38,
 10,
 25,
 46,
 10,
 21,
 24,
 29,
 36,
 25,
 24]

In [42]:
np.mean(my_cricket_score)

27.35

null_hyphothesis=sample mean should be 27.35

In [43]:
virat_cricket_score=[33, 45, 23, 25, 46, 46, 46, 49, 49, 14, 14, 44, 25, 31, 25, 40, 30,20, 42, 37]

In [44]:
np.mean(virat_cricket_score)

34.2

In [45]:
from scipy import stats

In [46]:
import scipy
result=scipy.stats.ttest_1samp(my_cricket_score,15)

In [47]:
result[1]


0.0005939030580482863

 we are going to reject the null hyphothesis
p_value<=0.05

#if P_value we are going to accept the null hyphgothesis
p_value>0.05

In [48]:
scipy.stats.ttest_1samp(my_cricket_score,27) ## accept

Ttest_1sampResult(statistic=0.1165211062024157, pvalue=0.9084623785416334)

In [49]:
scipy.stats.ttest_1samp(my_cricket_score,15)  ## reject

Ttest_1sampResult(statistic=4.111530461713794, pvalue=0.0005939030580482863)

In [50]:
#two-sample t test(with respect to two independent sample)
my_cricket_score=[22, 38, 19, 15, 48, 11, 10, 49, 47, 38, 10, 25, 46, 10, 21, 24, 29,36, 25, 24]

virat_cricket_score=[33, 45, 23, 25, 46, 46, 46, 49, 49, 44, 44, 49, 25, 31, 25, 40, 30,20, 42, 37]

In [51]:
first_sample_mean=np.mean(my_cricket_score)
second_sample_mean=np.mean(virat_cricket_score)

In [52]:
print(first_sample_mean)
print(second_sample_mean)

27.35
37.45


my_null_hyphothsis=both sample mean will be same

In [53]:
scipy.stats.ttest_ind(my_cricket_score,virat_cricket_score)   # reject

Ttest_indResult(statistic=-2.7009890879565885, pvalue=0.010269464981935)

In [55]:
#paired t-test(two sample from the sample population on different time interval)
my_cricket_score_from_first_inning=[22, 38, 19, 15, 48, 11, 10, 49, 47, 38, 10, 25, 46, 10, 21, 24, 29,36, 25, 24]
my_cricket_score_from_second_inning=[22, 38, 29, 15, 18, 11, 10, 49, 47, 38, 50, 45, 46, 40, 21, 24, 29,16, 25, 24]

In [56]:
print(np.mean(my_cricket_score_from_first_inning))
print(np.mean(my_cricket_score_from_second_inning))

27.35
29.85


In [57]:
scipy.stats.ttest_rel(my_cricket_score_from_first_inning,my_cricket_score_from_second_inning)

Ttest_relResult(statistic=-0.7542295906745516, pvalue=0.45995773816634733)

accept the null hypothesis 

# CHI -SQURE TEST


In [60]:
import seaborn as sns


In [65]:
import pandas as pd
pd.read_csv("tips.csv")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [68]:
dataset = pd.read_csv("tips.csv")

In [69]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [72]:
dataset.columns


Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [73]:
dataset[['sex','smoker']]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [74]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])

In [85]:
dataset_array=dataset_table.values

In [81]:
import scipy.stats as stats

stats.chi2_contingency()   ##chi2 = chisquare

In [86]:
dataset_array


array([[54, 33],
       [97, 60]], dtype=int64)

In [87]:
print(f"observed value(real value) \n {dataset_array}")

observed value(real value) 
 [[54 33]
 [97 60]]


In [88]:
stats.chi2_contingency(dataset_array)

(0.0,
 1.0,
 1,
 array([[53.84016393, 33.15983607],
        [97.15983607, 59.84016393]]))

In [89]:
stats_test,p,dof,expected_values=stats.chi2_contingency(dataset_array)

In [90]:
p

1.0

In [92]:
expected_values


array([[53.84016393, 33.15983607],
       [97.15983607, 59.84016393]])

In [95]:
dataset_table

smoker  No  Yes
sex            
Female  54   33
Male    97   60

In [94]:
dataset_table.iloc[0:2,0]

sex
Female    54
Male      97
Name: No, dtype: int64

In [97]:
dataset_table.iloc[0,0:2]

smoker
No     54
Yes    33
Name: Female, dtype: int64

In [98]:
no_of_rows=dataset_table.iloc[0:2,0]

In [99]:
no_of_column=dataset_table.iloc[0,0:2]

In [100]:
len(no_of_rows)

2

In [101]:
len(no_of_column)

2

In [103]:
dof=(len(no_of_column)-1)*(len(no_of_rows)-1)

In [104]:
dof

1

In [107]:
for o,e in zip(Observed_Values,expected_values):
    print(o,e)

[54 33] [53.84016393 33.15983607]
[97 60] [97.15983607 59.84016393]


In [108]:
from scipy.stats import chi2
chisqure_test=sum([(o-e)**2./e for o,e in zip(Observed_Values,expected_values)])

In [109]:
chisqure_test

array([0.00073745, 0.00119737])

In [111]:
alpha=0.05


In [117]:
chi_square_statistic=chisqure_test[0]+chisqure_test[1]


In [118]:
dof

1

In [119]:
from scipy.stats import chi2
critical_value=chi2.ppf(1-alpha,df=dof)

In [120]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")


Retain H0,There is no relationship between 2 categorical variables


In [121]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=dof)

In [122]:
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables
